version: '3.8'

services:
  mq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  server:
    build:
      context: ./Backend
    ports:
      - 4500:4500
      - 5000:5000
    restart: always
  crawlers:
    build:
      context: ./Crawlers
    restart: always
    depends_on:
      - mq
    ports:
      - 127.0.0.1:12288:12288
